### ISSUE TITLE
[Enhancement] Have dispensers breed animals

### ISSUE THREAD

**Issue by Tofugrass** [cseven/SmartDispensers#2]
Having dispensers breed animals would really round out this mod I believe. I looked around at other ones, and it seems not too trivial to implement, because of overlapping animal hitboxes I would imagine.

**Comment by cseven** [comment]
I agree - that definitely fits within the scope of the mod. It also wouldn't be too difficult to implement:
- Get the animals in the area directly in front of the dispenser (see sword code, or vanilla shears)
- Find the first animal in the list (randomly ordered) that is both 1. able to be bred with the item in question and 2. doesn't have a breeding cooldown active
- With the animal from above, set its breeding state accordingly and subtract one from the dispenser stack.

The only issue is that there is an overlap with carrots and seeds (both can be planted, but are also used for breeding pigs and chicken respectively). Dispensers do not support having multiple behaviors for a single item type, so there would have to be some strange special cases happening here (but planting should definitely have priority over breeding, in any case).

**Comment by cseven** [comment]
A more extensible system would be to create some sort of nested structure for behaviors, where there is some sort of "top-level" behavior for situations like this and it, upon firing, attempts to use each of the behaviors in its list in turn, stopping when one successfully executes (defaults to just popping the item out, as one would expect). That shouldn't be _too_ difficult to do, and would make more complex behaviors much more manageable should I choose to extend this mod further.

**Comment by cseven** [comment]
Implemented in version 1.4

**Comment by Tofugrass** [comment]
Is there any chance you could update the mod to include the MIT License so it works with forge 1.16.2+ ?

**Comment by cseven** [comment]
The license has nothing to do with the working forge versions - this mod
was written back before Forge 1.16.2 was available. Once I figure out what
the update process is from 1.15.2 to 1.16.2 I'll push an updated version. I
suspect it is relatively easy, as the 1.16 update did not change anything
that I take advantage of in this mod.
